name: 'ggshield-action'
description: 'Scan commits for hardcoded secrets and security policy breaks'
branding:
  icon: 'shield'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ggshield
    - -v
    - secret
    - scan
    - ci
